plot_tanzaku:plot_tanzaku.cpp
	g++ -o plot_tanzaku plot_tanzaku.cpp -lglut -lGLU -lGL -lm
plot_stripe:plot_stripe.cpp
	g++ -o plot_stripe plot_stripe.cpp -lglut -lGLU -lGL -lm
cal_w1:cal_w1.cpp
	g++ -o cal_w1 cal_w1.cpp -lglut -lGLU -lGL -lm
cal_wn:cal_wn.cpp
	g++ -o cal_wn cal_wn.cpp -lglut -lGLU -lGL -lm
