background:background.cpp
	g++ -o background background.cpp -lssm -lm
back:back.cpp
	g++ -g -o back back.cpp -lssm -lm
filter:filter.cpp
	g++ -o filter filter.cpp Step.cpp mystd.cpp -lssm -lm
connect:connect.c
	gcc -o connect connect.c -lssm -lm
rp:rp.c
	gcc -o rp rp.c -lssm -lm
connect2:connect2.cpp
	g++ -o connect2 connect2.cpp -lssm -lm
connect_new:connect_new.cpp
	g++ -o connect_new connect_new.cpp -lssm -lm
scandataR2:scandataR2.cpp
	gcc scandataR2.cpp  -lglut -lGLU -lGL -lm -lssm -o scandataR2
LS3DViewer:LS3DViewer.cpp
	g++ -o LS3DViewer LS3DViewer.cpp  -lglut -lGLU -lGL -lm -lssm
objectR:objectR.cpp
	g++ -o objectR objectR.cpp  -lglut -lGLU -lGL -lm -lssm
