door_simu:door_simu.cpp
	g++ -o door_simu door_simu.cpp read.cpp -lglut -lGLU -lGL
test:test.cpp
	g++ -o test test.cpp -lglut -lGLU -lGL
timer_test:timer_test.cpp
	g++ -o timer_test timer_test.cpp -lglut -lGLU -lGL
